#!/usr/bin/env bash
# GameCenter Mac mini build machine — one-shot setup.
#
# Run ON the Mac mini (10.98.8.188) that will build Cocos Creator games.
#
# Usage:
#   bash ops/scripts/setup-gamecenter-mac-build.sh
#
# What this does:
#   1. Creates ~/dev/gamecenter-server workspace
#   2. Copies pipeline scripts into ~/dev/mchat/ops/scripts/
#   3. Generates gamecenter-local.env with auto-detected Cocos Creator path
#   4. Tests SSH connectivity back to the MChat server (10.98.8.15)
#   5. Prints next steps (SSH key, launchd, etc.)
set -euo pipefail

SERVER_HOST="${GAMECENTER_SERVER_HOST:-10.98.8.15}"
SERVER_USER="${GAMECENTER_SERVER_USER:-xiaoxiao}"
MAC_USER="$(whoami)"
LOCAL_GC="$HOME/dev/gamecenter-server"
MCHAT_DIR="$HOME/dev/mchat"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "============================================"
echo " GameCenter Mac Build Machine Setup"
 echo "  Mac user:   ${MAC_USER}"
 echo "  Server:     ${SERVER_USER}@${SERVER_HOST}"
 echo "  Workspace:  ${LOCAL_GC}"
 echo "============================================"
echo ""

# ── 1. Workspace ──
echo "==> [1/5] Create workspace"
mkdir -p "$LOCAL_GC"
echo "  OK: $LOCAL_GC"

# ── 2. Scripts ──
echo ""
echo "==> [2/5] Verify pipeline scripts"
if [[ ! -d "$MCHAT_DIR/ops/scripts" ]]; then
  echo "  Cloning mchat repo to $MCHAT_DIR ..."
  git clone https://git7654321.9235.net/feifei/mchat.git "$MCHAT_DIR" || {
    echo "  FAILED: could not clone mchat repo." >&2
    echo "  Alternative: rsync scripts from server:" >&2
    echo "    rsync -avz ${SERVER_USER}@${SERVER_HOST}:/opt/xiaoxiao/mchat/ops/scripts/ $MCHAT_DIR/ops/scripts/" >&2
    exit 1
  }
fi
echo "  Scripts at: $MCHAT_DIR/ops/scripts/"
chmod +x "$MCHAT_DIR"/ops/scripts/gamecenter-*.sh 2>/dev/null || true

# ── 3. Detect Cocos Creator ──
echo ""
echo "==> [3/5] Detect Cocos Creator installations"
COCOS_BINS=()
for app in /Applications/Cocos/Creator/*/CocosCreator.app; do
  [[ -d "$app" ]] || continue
  bin="$app/Contents/MacOS/CocosCreator"
  if [[ -x "$bin" ]]; then
    ver="$(basename "$(dirname "$app")")"
    COCOS_BINS+=("$ver|$bin")
    echo "  Found: Cocos Creator $ver → $bin"
  fi
done
# Also check non-versioned path
for app in /Applications/CocosCreator/CocosCreator.app; do
  [[ -d "$app" ]] || continue
  bin="$app/Contents/MacOS/CocosCreator"
  if [[ -x "$bin" ]]; then
    COCOS_BINS+=("unknown|$bin")
    echo "  Found: Cocos Creator (legacy) → $bin"
  fi
done
if [[ ${#COCOS_BINS[@]} -eq 0 ]]; then
  echo "  WARNING: No Cocos Creator found in /Applications." >&2
  echo "  Install Cocos Creator 3.x from https://www.cocos.com/creator-download" >&2
fi

# ── 4. Generate gamecenter-local.env ──
echo ""
echo "==> [4/5] Generate gamecenter-local.env"
ENV_FILE="$MCHAT_DIR/ops/scripts/gamecenter-local.env"
cat > "$ENV_FILE" <<ENVEOF
# Auto-generated by setup-gamecenter-mac-build.sh
# Mac mini: ${MAC_USER}@$(hostname 2>/dev/null || echo 'mac')

# SSH user on the MChat server
SSH_USER=${SERVER_USER}

# Local workspace for pulled projects
LOCAL_GAMECENTER=${LOCAL_GC}

# Server paths
REMOTE_GAMECENTER_ROOT=/opt/xiaoxiao/gamecenter
REMOTE_PROJECT_PARENT=src
REMOTE_MCHAT=/opt/xiaoxiao/mchat

# xcx workspace (used by sync scripts to resolve source_relpath: src/<category>/<slug>)
GAMECENTER_WORKSPACE=/Users/${MAC_USER}/dev/xcx

# Cocos Creator binary (first detected; edit if you have multiple versions)
ENVEOF

if [[ ${#COCOS_BINS[@]} -gt 0 ]]; then
  FIRST_BIN="${COCOS_BINS[0]#*|}"
  echo "COCOS_CREATOR_BIN=\"${FIRST_BIN}\"" >> "$ENV_FILE"
else
  echo '# COCOS_CREATOR_BIN="/Applications/Cocos/Creator/3.8.8/CocosCreator.app/Contents/MacOS/CocosCreator"' >> "$ENV_FILE"
fi

echo "" >> "$ENV_FILE"
echo "# Debug: set to 1 for verbose build output" >> "$ENV_FILE"
echo "GAMECENTER_BUILD_DEBUG=0" >> "$ENV_FILE"

echo "  Written: $ENV_FILE"
echo ""
cat "$ENV_FILE"

# ── 5. Test SSH back to server ──
echo ""
echo "==> [5/5] Test SSH to server ${SERVER_HOST}"
if ssh -o BatchMode=yes -o ConnectTimeout=5 "${SERVER_USER}@${SERVER_HOST}" "echo OK" 2>/dev/null; then
  echo "  SSH OK: can reach server without password."
else
  echo "  SSH FAILED: server cannot reach this Mac yet." >&2
  echo ""
  echo "  To set up SSH key from server to this Mac:" >&2
  echo "    1. On server (ssh ${SERVER_USER}@${SERVER_HOST}):" >&2
  echo "       ssh-keygen -t ed25519 -f ~/.ssh/id_gamecenter_build -N ''" >&2
  echo "    2. Copy public key to this Mac:" >&2
  echo "       ssh-copy-id -i ~/.ssh/id_gamecenter_build.pub ${MAC_USER}@$(ipconfig getifaddr en0 2>/dev/null || echo '10.98.8.188')" >&2
  echo "    3. Test: ssh -i ~/.ssh/id_gamecenter_build ${MAC_USER}@10.98.8.188 'echo OK'" >&2
fi

echo ""
echo "============================================"
echo " Setup complete!"
echo ""
echo " Next steps:"
echo "   1. Install Cocos Creator (if not found above)"
echo "   2. Set up SSH key from server → this Mac"
echo "   3. On the server, update .env:"
echo "      GAMECENTER_BUILD_SSH_HOST=10.98.8.188"
echo "      GAMECENTER_BUILD_SSH_USER=${MAC_USER}"
echo "      GAMECENTER_BUILD_PIPELINE_SCRIPT=${MCHAT_DIR}/ops/scripts/gamecenter-local-pipeline.sh"
echo "      GAMECENTER_DEPLOY_HOST=${SERVER_HOST}"
echo "      # Remove GAMECENTER_BUILD_AGENT_URL (Windows agent no longer needed)"
echo "   4. Test build from server:"
echo "      ssh ${SERVER_USER}@${SERVER_HOST} 'bash /opt/xiaoxiao/mchat/ops/scripts/gamecenter-remote-pipeline-build.sh <slug>'"
echo "============================================"
